### ISSUE TITLE
함수명이 Async.... 비동기로 처리되는건가염 .. ?

### ISSUE THREAD

**Issue by hyodii** [houmuch-kr/houmuch-api#4]
함수명이 Async.... 비동기로 처리되는건가염 .. ?

_Originally posted by @youspend8 in https://github.com/houmuch-kr/houmuch-api/pull/3#discussion_r1071680919_

**Comment by hyodii** [comment]
issues를 만들어봤어요...!

**Comment by ggumi** [comment]
java에서 비동기처리(특정 코드의 실행이 완료될 때까지 기다리지 않고 다음 코드를 먼저 수행)하려면 멀티스레드 사용하나 봐요?
함수형인터페이스로 callback, future 사용 등등(코드는 아직 이해 못함)

react에선 fetch() 가 비동기 함수래요
근데 api 값 가져오기 전에 화면에 뿌려주면 오류나니까
값 다 가져온 후에 
.then() 으로 동기적 처리해서 화면에 뿌려주는?

출처 : 자바 비동기
https://velog.io/@pllap/Java%EC%97%90%EC%84%9C%EC%9D%98-%EB%B9%84%EB%8F%99%EA%B8%B0-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D

: 리액트 비동기
https://velog.io/@0xjuchan/React-fetch-%ED%95%A8%EC%88%98%EC%99%80-%EB%B9%84%EB%8F%99%EA%B8%B0%EC%B2%98%EB%A6%AC-feat.-JSON

**Comment by youspend8** [comment]
우선 멀티쓰레드와 싱글쓰레드의 환경에서 사용자 N명의 요청이 어떤식으로 처리되는가에 대해 알아보면 좋을것 같고
react의 fetch() 함수는 비동기 함수라기보다는
데이터를 API를 통해 요청할 때 XHR 방식으로 요청하고자 필요한 함수라고 보면 될 것 같습니다.
